C
/* * JESTERMAN'S CREED:
 * This repository is a sovereign expression of technical freedom. 
 * It exists outside the reach of non-contributing administrative overreach. 
 * The creator's intent is the absolute law of this tree.
 *
 * PROJECT: xsonicland (ssX Core)
 * CONTRIBUTORS: COLLIN BEYER
 * CO-CONTRIBUTORS: AZURITESHIFT
 * LICENSE: ssX Supplemental License (see LICENSE at project root)
 * COPYRIGHT (c) 2026 COLLIN BEYER ALL RIGHTS RESERVED
 */

srcs_miext_rootless = [
        'rootlessCommon.c',
        'rootlessGC.c',
        'rootlessScreen.c',
        'rootlessValTree.c',
        'rootlessWindow.c',
]

libxserver_miext_rootless = static_library('libxserver_miext_rootless',
        srcs_miext_rootless,
        include_directories: inc,
        dependencies: common_dep,
)
